FROM ubuntu:latest 
RUN apt-get update && apt-get install -y python3 \ python3-pip 
RUN pip3 install jupyter
WORKDIR /home/jupyter/
COPY  /Desktop/Work/Projects/intro_to_docker/ ./
EXPOSE 8000
ENTRYPOINT ["jupyter", "notebook", "--ip=*"]